logging:
  file:
    path: logs
  level:
    org.springframework.web: Debug
server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/taqaddam
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true

#application:
#  security:
#    jwt:
#      security-key: 068E18D8B4A10A27216489CC6D1D2B4427ACCAE0CEBD1709EA0ADB5957AE1DD9
#      expiration:









